name: Deploy (cPanel)

on:
  push:
    branches: [ "main" ]   # ajusta a tua branch

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # (Opcional) Build do teu projecto: ajusta conforme stack
      - name: Build (opcional)
        run: |
          if [ -f package.json ]; then npm ci && npm run build; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt --target ./python_packages; fi
          # adiciona outros passos de build/empacotamento conforme necessário

      - name: Deploy via FTPS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftps
          port: 21
          #local-dir: ./   # termina com /
          server-dir: ../   # termina com /
          # server-dir: /public_htmlx/   # termina com /
          exclude: |
            **/.git*
            **/.github/**
            **/node_modules/**
            **/tests/**
            **/.vscode/**
          # dry-run: true   # ativa para testar sem enviar
